name: docker-compose
description: A generated Helm Chart for docker-compose from Skippbox Kompose
version: 0.0.1
apiVersion: v1
keywords:
  - docker-compose
sources:
home:
icon: https://golang.org/lib/godoc/images/go-logo-blue.svg